apiVersion: v1
kind: Namespace
metadata:
  name: whoami-example
  labels:
    shared-gateway-access: "true"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whoami-cert
  namespace: whoami-example
spec:
  secretName: whoami-cert
  dnsNames:
    - "whoami.cluster.stevenchen.one"
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: whoami-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          env:
            - name: WHOAMI_PORT_NUMBER
              value: "8080"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: whoami-example
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: whoami
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: whoami
  namespace: whoami-example
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - kind: Secret
            name: whoami-cert
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: whoami
  namespace: whoami-example
spec:
  parentRefs:
    - name: whoami
  hostnames:
    - "whoami.cluster.stevenchen.one"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: whoami
          port: 80
