apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whoami-cert
spec:
  secretName: whoami-cert
  dnsNames:
    - "whoami.cluster.stevenchen.one"
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
