machine:
  kubelet:
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
  install:
    disk: /dev/vda
cluster:
  network:
    cni:
      name: none
  proxy:
    disabled: true
