server:
  env:
    WOODPECKER_HOST: "https://woodpecker.cluster.stevenchen.one"
    WOODPECKER_ADMIN: "steven"
    WOODPECKER_OPEN: true
    WOODPECKER_GITEA: true
    WOODPECKER_GITEA_URL: "https://gitea.cluster.stevenchen.one"
    WOODPECKER_GITEA_CLIENT: "clientclientclientclientclient"
    WOODPECKER_GITEA_SECRET: "secretsecretsecretsecretsecret"
  persistentVolume:
    size: "1Gi"
agent:
  env:
    WOODPECKER_BACKEND_K8S_VOLUME_SIZE: "1Gi"
  persistence:
    size: "1Gi"